<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('products', function (Blueprint $table) {
            $table->id();

            // 1. Core Product Information
            $table->string('name');
            $table->string('brand');    // Required by Admin Panel
            $table->string('category'); // Required by Admin Panel
            
            // 2. Details
            $table->string('slug')->nullable(); // Auto-generated by Model
            $table->text('description')->nullable(); // Required by Admin Panel

            // 3. Pricing and Stock
            $table->decimal('price', 10, 2); 
            $table->integer('quantity'); // Matches Admin Panel input name

            // 4. Media
            // Using longText to support very long Google Image URLs
            $table->longText('image');   // Matches Admin Panel input name
            
            $table->boolean('is_active')->default(true);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('products');
    }
};